# This file can be used to override defaults for multirun arguments.
# Arguments of the SimPathsMultiRun object overridden by the command-line

maxNumberOfRuns: 1
executeWithGui: false
randomSeed: 606
startYear: 2019
endYear: 2032
popSize: 5000

# Arguments passed to the SimPathsModel
model_args:
#    maxAge: 130
#    fixTimeTrend: true
#    timeTrendStopsIn: 2017
#    fixRandomSeed: true
#    sIndexTimeWindow: 5
#    sIndexAlpha: 2
#    sIndexDelta: 0
#    savingRate: 0
#    initialisePotentialEarningsFromDatabase: true
#    useWeights: false
#    useSBAMMatching:
#    projectMortality: true
#    labourMarketCovid19On: false
#    projectFormalChildcare: true
#    donorPoolAveraging: true
#    alignFertility: true
#    alignEmployment: false
    alignCohabitation: false
    alignPopulation: false
    projectSocialCare: true
#    enableIntertemporalOptimisations: true
#    responsesToLowWageOffer: false
#    saveImperfectTaxDBMatches: false
#    useSavedBehaviour: false
#    readGrid: "laptop serial"
#    saveBehaviour: true
#    employmentOptionsOfPrincipalWorker: 3
#    employmentOptionsOfSecondaryWorker: 3
#    responsesToEducation: true
#    responsesToRetirement: false
#    responsesToHealth: true
#    responsesToDisability: false
#    minAgeForPoorHealth: 50
#    responsesToRegion: false

# Arguments that alter processing of the SimPathsMultiRun object
innovation_args:
    randomSeedInnov: false
#    intertemporalElasticityInnov: false
#    labourSupplyElasticityInnov: true

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0